numberOfThreads: 5

metricPrefix:  "Custom Metrics|AzureMonitor|"

clientId: ""

tenantId: ""

clientKey: ""

subscriptionId: ""

api-version: "2017-05-10"

monitor-api-version: "2017-05-01-preview"

filter:
  - resourceType: "Microsoft.AnalysisServices/servers"
  - resourceType: "Microsoft.ApiManagement/service"
  - resourceType: "Microsoft.Automation/automationAccounts"
  - resourceType: "Microsoft.Batch/batchAccounts"
  - resourceType: "Microsoft.Cache/redis"
  - resourceType: "Microsoft.ClassicCompute/virtualMachines"
  - resourceType: "Microsoft.CognitiveServices/accounts"
  - resourceType: "Microsoft.Compute/virtualMachines"
  - resourceType: "Microsoft.Compute/virtualMachineScaleSets"
  - resourceType: "Microsoft.Compute/virtualMachineScaleSets/virtualMachines"
  - resourceType: "Microsoft.CustomerInsights/hubs"
  - resourceType: "Microsoft.DataLakeAnalytics/accounts"
  - resourceType: "Microsoft.DataLakeStore/accounts"
  - resourceType: "Microsoft.DBforMySQL/servers"
  - resourceType: "Microsoft.DBforPostgreSQL/servers"
  - resourceType: "Microsoft.Devices/IotHubs"
  - resourceType: "Microsoft.Devices/provisioningServices"
  - resourceType: "Microsoft.DocumentDB/databaseAccounts"
  - resourceType: "Microsoft.EventHub/namespaces"
  - resourceType: "Microsoft.Insights/AutoscaleSettings"
  - resourceType: "Microsoft.Logic/workflows"
#  - resourceType: "Microsoft.Network/loadBalancers" -- Produced Errors during Test
  - resourceType: "Microsoft.Network/publicIPAddresses"
  - resourceType: "Microsoft.Network/applicationGateways"
  - resourceType: "Microsoft.Network/virtualNetworkGateways"
  - resourceType: "Microsoft.Network/expressRouteCircuits"
  - resourceType: "Microsoft.Network/trafficManagerProfiles"
  - resourceType: "Microsoft.NotificationHubs/Namespaces/NotificationHubs"
  - resourceType: "Microsoft.Search/searchServices"
  - resourceType: "Microsoft.ServiceBus/namespaces"
  - resourceType: "Microsoft.Sql/servers/databases"
  - resourceType: "Microsoft.Sql/servers/elasticPools"
  - resourceType: "Microsoft.Sql/servers"
  - resourceType: "Microsoft.Storage/storageAccounts"
  - resourceType: "Microsoft.Storage/storageAccounts/blobServices"
  - resourceType: "Microsoft.Storage/storageAccounts/tableServices"
  - resourceType: "Microsoft.Storage/storageAccounts/queueServices"
  - resourceType: "Microsoft.Storage/storageAccounts/fileServices"
  - resourceType: "Microsoft.StreamAnalytics/streamingjobs"
  - resourceType: "Microsoft.Web/serverfarms"
  - resourceType: "Microsoft.Web/sites"
  - resourceType: "Microsoft.Web/sites/slots"
  - resourceType: "Microsoft.Web/hostingEnvironments/multiRolePools"
  - resourceType: "Microsoft.Web/hostingEnvironments/workerPools"